# Generated by Django 2.0.3 on 2019-04-30 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.IntegerField(verbose_name='就诊码')),
                ('status', models.PositiveIntegerField(choices=[(1, '确认'), (2, '取消'), (3, '等待'), (4, '失效')], verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预约就诊',
                'verbose_name_plural': '预约就诊',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.PositiveIntegerField(choices=[(1, '08:00 - 09:00'), (2, '09:00 - 10:00'), (3, '10:00 - 11:00'), (4, '11:00 - 12:00'), (5, '12:00 - 14:00'), (6, '14:00 - 15:00'), (7, '15:00 - 16:00'), (8, '16:00 - 15:00'), (9, '17:00 - 18:00')], verbose_name='时间段')),
                ('date', models.DateField(verbose_name='日期')),
                ('residual_num', models.IntegerField(verbose_name='剩余号量')),
                ('patients', models.IntegerField(default=0, verbose_name='就诊人数')),
            ],
            options={
                'verbose_name': '时刻表',
                'verbose_name_plural': '时刻表',
            },
        ),
    ]
