# Generated by Django 2.0.3 on 2019-04-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('users', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Outpatient', verbose_name='门诊部'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.DoctorSchedule', verbose_name='预约时刻表'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='患者'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'time_range', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctor_schedule')},
        ),
    ]
