# Generated by Django 2.0.3 on 2019-04-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.DoctorSchedule', verbose_name='预约时刻表'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Outpatient', verbose_name='诊室'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '确认'), (2, '取消'), (3, '等待'), (4, '失效')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_no',
            field=models.IntegerField(verbose_name='就诊码'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='residual_num',
            field=models.IntegerField(verbose_name='剩余号量'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='time_range',
            field=models.PositiveIntegerField(choices=[(1, '08:00 - 09:00'), (2, '09:00 - 10:00'), (3, '10:00 - 11:00'), (4, '11:00 - 12:00'), (5, '12:00 - 14:00'), (6, '14:00 - 15:00'), (7, '15:00 - 16:00'), (8, '16:00 - 15:00'), (9, '17:00 - 18:00')], verbose_name='时间段'),
        ),
    ]
