# Generated by Django 2.0.3 on 2019-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='order_no',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='订单号'),
        ),
    ]
