# Generated by Django 2.0.3 on 2019-04-23 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='医院名')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='市')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='区')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='经度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='纬度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医院信息',
                'verbose_name_plural': '医院信息',
            },
        ),
        migrations.CreateModel(
            name='HospitalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级目录'), (2, '二级目录'), (3, '三级目录')], help_text='类目级别', verbose_name='类目级别')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='hospital.HospitalCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '科室类别',
                'verbose_name_plural': '科室类别',
            },
        ),
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpatient_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='门诊名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department', verbose_name='科室')),
                ('department_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpatient', to='hospital.HospitalCategory', verbose_name='科室类别')),
            ],
            options={
                'verbose_name': '门诊信息',
                'verbose_name_plural': '门诊信息',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.HospitalCategory', verbose_name='科室类别'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hospital.HospitalCategory', verbose_name='科室类别'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='医院'),
        ),
    ]
