# Generated by Django 2.0.3 on 2019-04-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='医院id'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=100, verbose_name='医院名'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='纬度'),
        ),
    ]
