# Generated by Django 2.0.3 on 2019-04-30 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账户'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hospital.HospitalCategory', verbose_name='机构类别'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='医院'),
        ),
        migrations.AlterUniqueTogether(
            name='outpatient',
            unique_together={('department', 'outpatient_name')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'department_name')},
        ),
    ]
