# Generated by Django 2.0.3 on 2019-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190422_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='科室名称'),
        ),
    ]
