# Generated by Django 2.0.3 on 2019-04-24 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190423_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalcategory',
            options={'verbose_name': '所属机构', 'verbose_name_plural': '所属机构'},
        ),
        migrations.AlterField(
            model_name='department',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='hospital.HospitalCategory', verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital.HospitalCategory', verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级机构'), (2, '二级机构'), (3, '三级机构')], help_text='机构级别', verbose_name='机构级别'),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='code',
            field=models.CharField(default='', help_text='机构code', max_length=30, verbose_name='机构code'),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='desc',
            field=models.TextField(default='', help_text='机构描述', verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='name',
            field=models.CharField(default='', help_text='机构名', max_length=30, verbose_name='机构名'),
        ),
        migrations.AlterField(
            model_name='hospitalcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父机构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='hospital.HospitalCategory', verbose_name='父机构级别'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department', verbose_name='所属科室'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='department_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpatient', to='hospital.HospitalCategory', verbose_name='机构类别'),
        ),
    ]
