# Generated by Django 2.0.3 on 2019-04-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('hospital', '0002_auto_20190429_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='医院'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='outpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Outpatient', verbose_name='诊室'),
        ),
    ]
