# Generated by Django 2.0.3 on 2019-04-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190424_1707'),
        ('users', '0002_auto_20190423_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayschedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='outpatient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.Outpatient', verbose_name='诊室'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department', verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='医生工号'),
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
    ]
