# Generated by Django 2.0.3 on 2019-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
