# Generated by Django 2.0.3 on 2019-04-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190424_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='outpatient',
        ),
    ]
