# Generated by Django 2.0.3 on 2019-04-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190422_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
