# Generated by Django 2.0.3 on 2019-04-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190424_1707'),
        ('users', '0005_remove_doctor_outpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='outpatient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.Outpatient', verbose_name='诊室'),
        ),
    ]
